#!/bin/bash

rm -rf ports
mkdir ports

ln -s /dev/ttyACM0 ports/receiver
ln -s /dev/ttyACM1 ports/sender

# ln -s /dev/serial/by-path/platform-tegra-xhci-usb-0\:3.3.4\:1.0 ports/receiver
# ln -s /dev/serial/by-path/platform-tegra-xhci-usb-0\:3.3.3\:1.0 ports/sender
